[versions]
coilCompose = "3.3.0"
composeShimmer = "1.3.3"
constraintlayoutCompose = "1.1.1"
dotsindicator = "5.1.0"
materialKolor = "3.0.0"
minSdk = "21"
targetSdk = "36"
compileSdk = "36"
ndkVersion = "28.2.13676358"
javaVersion = "17"

# Android Tools
desugarJdkLibs = "2.1.5"
expandablelayout = "2.9.2"
flexbox = "3.0.0"
hiltAndroid = "2.56.2"
hiltAndroidCompiler = "2.56.2"
interpolator = "1.0.0"
junit = "4.13.2"
multidex = "2.0.1"

# AndroidX - UI
# noinspection GradleDependency
androidxViewpager2 = "1.1.0-beta02"
# noinspection GradleDependency
androidxConstraintlayout = "2.1.4"
androidxSwiperefreshlayout = "1.1.0"
# noinspection GradleDependency
androidxAsynclayoutinflater = "1.0.0"
# noinspection GradleDependency
androidxRecyclerview = "1.3.1"
# noinspection GradleDependency
androidxTransition = "1.5.0"

# AndroidX - Core/Ktx
androidxCoreKtx = "1.17.0"
androidxActivityKtx = "1.10.1"
androidxFragmentKtx = "1.6.2"

# AndroidX - Lifecycle
androidxLifecycleViewmodelKtx = "2.9.4"
androidxLifecycleRuntimeKtx = "2.9.4"

# AndroidX - Data
# noinspection GradleDependency
androidxDatastore = "1.0.0"

# AndroidX - Room
# noinspection GradleDependency
androidxRoom = "2.6.0"

# AndroidX - Navigation
# noinspection GradleDependency
androidxNavigation = "2.7.4"

# AndroidX - Paging
# noinspection GradleDependency
pagingRuntimeKtx = "3.2.1"
pagingCompose = "3.2.1"

# AndroidX - Appcompat
# noinspection GradleDependency
androidxAppcompat = "1.7.1"

# Compose
compose = "2.9.0"
composeBom = "2025.10.00"
activityCompose = "1.10.1"
navigationCompose = "2.9.3"
hiltNavigationCompose = "1.2.0"
wearCompose = "1.5.3"

# Google Material
# noinspection GradleDependency
material = "1.12.0-alpha01"

# ZXing
# noinspection GradleDependency
orgEclipseJgit = "7.2.0.202503040940-r"
# noinspection GradleDependency
preferenceKtx = "1.2.1"
protobufJavalite = "4.31.1"
# noinspection GradleDependency
wear = "1.3.0"
# noinspection GradleDependency
zxingCore = "3.3.0"

# Kotlin
kotlinCoroutinesAndroid = "1.10.2"

# Third Party - UI/Adapters
multitype = "4.3.0"
photoview = "2.3.0"

# Third Party - Network
okhttp3CompatOkhttp = "5.0.0-p2"
retrofit2Compat = "2.12.0-p2"
# noinspection GradleDependency
googleGson = "2.9.1"

# Third Party - Other
geetestSensebot = "4.4.4"
brotliDec = "0.1.2"
brotli4j = "1.18.0"
xlog = "1.11.1"
agp = "8.13.2"
# noinspection GradleDependency
kotlin = "2.1.20"
# noinspection GradleDependency
ksp = "2.1.20-1.0.31"
hilt = "2.56.2"
protobufPlugin = "0.9.5"
# noinspection GradleDependency
junitVersion = "1.1.5"
espressoCore = "3.6.1"
materialPreferences = "1.0.1"

materialthemebuilder = "1.5.1"

shimmer = "0.5.0"
skeleton = "2.0.1"
splittiesFunPackAndroidBase = "3.0.0"

[libraries]
# Android Tools
androidx-constraintlayout-compose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayoutCompose" }
androidx-datastore = { module = "androidx.datastore:datastore", version.ref = "androidxDatastore" }
androidx-interpolator = { module = "androidx.interpolator:interpolator", version.ref = "interpolator" }
androidx-paging-runtime-ktx = { module = "androidx.paging:paging-runtime-ktx", version.ref = "pagingRuntimeKtx" }
androidx-paging-compose = { module = "androidx.paging:paging-compose", version.ref = "pagingCompose" }
androidx-preference-ktx = { module = "androidx.preference:preference-ktx", version.ref = "preferenceKtx" }
androidx-transition = { module = "androidx.transition:transition", version.ref = "androidxTransition" }
coil-network-okhttp = { module = "io.coil-kt.coil3:coil-network-okhttp", version.ref = "coilCompose" }
coil-compose = { module = "io.coil-kt.coil3:coil-compose", version.ref = "coilCompose" }
compose-shimmer = { module = "com.valentinilk.shimmer:compose-shimmer", version.ref = "composeShimmer" }
desugar-jdk-libs = { group = "com.android.tools", name = "desugar_jdk_libs", version.ref = "desugarJdkLibs" }
dotsindicator = { module = "com.tbuonomo:dotsindicator", version.ref = "dotsindicator" }
expandablelayout = { module = "com.github.cachapa:ExpandableLayout", version.ref = "expandablelayout" }
flexbox = { module = "com.google.android.flexbox:flexbox", version.ref = "flexbox" }
hilt-android-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hiltAndroidCompiler" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hiltAndroid" }
junit = { module = "junit:junit", version.ref = "junit" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinCoroutinesAndroid" }
material-kolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
multidex = { group = "androidx.multidex", name = "multidex", version.ref = "multidex" }

# AndroidX - UI
androidx-viewpager2 = { group = "androidx.viewpager2", name = "viewpager2", version.ref = "androidxViewpager2" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-swiperefreshlayout = { group = "androidx.swiperefreshlayout", name = "swiperefreshlayout", version.ref = "androidxSwiperefreshlayout" }
androidx-asynclayoutinflater = { group = "androidx.asynclayoutinflater", name = "asynclayoutinflater", version.ref = "androidxAsynclayoutinflater" }
androidx-recyclerview = { group = "androidx.recyclerview", name = "recyclerview", version.ref = "androidxRecyclerview" }

# AndroidX - Core/Ktx
androidx-core = { group = "androidx.core", name = "core", version.ref = "androidxCoreKtx" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "androidxActivityKtx" }
androidx-fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "androidxFragmentKtx" }

# AndroidX - Lifecycle
androidx-lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "androidxLifecycleViewmodelKtx" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "androidxLifecycleRuntimeKtx" }

# AndroidX - Data
androidx-datastore-preferences = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "androidxDatastore" }

# AndroidX - Room
androidx-room-runtime = { group = "androidx.room", name = "room-runtime", version.ref = "androidxRoom" }
androidx-room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "androidxRoom" }
androidx-room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "androidxRoom" }

# AndroidX - Navigation
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }

# AndroidX - Appcompat
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }

# Google Material
# material = { group = "com.google.android.material", name = "material", version.ref = "material" }
# Use forked materialcompat library
material = { group = "com.huanli233.materialcompat", name = "material", version.ref = "material" }

# ZXing
org-eclipse-jgit = { module = "org.eclipse.jgit:org.eclipse.jgit", version.ref = "orgEclipseJgit" }
protobuf-javalite = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobufJavalite" }
shimmer = { module = "com.facebook.shimmer:shimmer", version.ref = "shimmer" }
skeleton = { module = "com.skywalkerdarren:skeleton", version.ref = "skeleton" }
splitties-fun1-pack-android-base = { module = "com.louiscad.splitties:splitties-fun-pack-android-base", version.ref = "splittiesFunPackAndroidBase" }
splitties-fun1-pack-android-material-components = { module = "com.louiscad.splitties:splitties-fun-pack-android-material-components", version.ref = "splittiesFunPackAndroidBase" }
zxing-core = { group = "com.google.zxing", name = "core", version.ref = "zxingCore" }

# Kotlin
kotlinx-coroutines-android = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "kotlinCoroutinesAndroid" }

# Third Party - UI/Adapters
multitype = { group = "com.drakeet.multitype", name = "multitype", version.ref = "multitype" }
photoview = { group = "com.github.chrisbanes", name = "PhotoView", version.ref = "photoview" }

# Third Party - Network
okhttp3-compat-okhttp = { group = "com.huanli233.okhttp3-compat", name = "okhttp", version.ref = "okhttp3CompatOkhttp" }
retrofit2-compat-retrofit = { group = "com.huanli233.retrofit2-compat", name = "retrofit", version.ref = "retrofit2Compat" }
retrofit2-compat-converter-gson = { group = "com.huanli233.retrofit2-compat", name = "converter-gson", version.ref = "retrofit2Compat" }
google-gson = { group = "com.google.code.gson", name = "gson", version.ref = "googleGson" }

# Third Party - Other
geetest-sensebot = { group = "com.geetest.sensebot", name = "sensebot", version.ref = "geetestSensebot" }
brotli-dec = { group = "org.brotli", name = "dec", version.ref = "brotliDec" }
brotli4j = { group = "com.aayushatharva.brotli4j", name = "brotli4j", version.ref = "brotli4j" }
xlog = { group = "com.elvishew", name = "xlog", version.ref = "xlog" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
materialpreferences = { group = "com.huanli233.materialpreferences", name = "preferences", version.ref = "materialPreferences" }

# Compose
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-navigation-compose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
androidx-hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxLifecycleRuntimeKtx" }
androidx-material-icons-extended = { module = "androidx.compose.material:material-icons-extended" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-foundation-pager = { group = "androidx.compose.foundation", name = "viewpager2" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-wear-navigation = { group = "androidx.'wear.compose", name = "compose-navigation", version.ref = "wearCompose" }
androidx-wear-material3 = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "wearCompose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufPlugin" }
kapt = { id = "org.jetbrains.kotlin.kapt", version.ref = "kotlin" }
parcelize = { id = "org.jetbrains.kotlin.plugin.parcelize", version.ref = "kotlin" }
materialthemebuilder = { id = "dev.rikka.tools.materialthemebuilder", version.ref = "materialthemebuilder" }
autoresconfig = { id = "dev.rikka.tools.autoresconfig", version = "1.2.2" }